on:
  push:
    tags:
      - v*

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repo
        uses: actions/checkout@v1
      - name: Install NodeJS
        uses: actions/setup-node@v1
        with:
          node-version: 16
      - name: Install pnpm
        uses: pnpm/action-setup@v2.1.0
        with:
          version: 6.22.2
      - name: Install deps
        run: pnpm install
      - name: Build Typescript
        run: pnpm build
       - uses: JS-DevTools/npm-publish@v1
        with:
          token: ${{ secrets.NPM_TOKEN }}